image:
  repository: harbor.yanello.net/docker/louislam/uptime-kuma
  tag: 2.1.3@sha256:32c352a235fd10f98b3f64a6a4345d3c0c7f4e8be7810d2e1e867f7fe2e48ba2

volume:
  storageClassName: truenas-ssd-nfs
  accessMode: ReadWriteMany

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists

externalDatabase:
  enabled: true
  hostname: mariadb
  port: 3306
  database: kuma
  existingSecret: mariadb-secrets
  existingSecretPasswordKey: MARIADB_PASSWORD
  existingSecretUsernameKey: MARIADB_USER
