image:
  repository: harbor.yanello.net/docker/louislam/uptime-kuma
  tag: 2.1.0@sha256:da418b1f5655c12d2d62aa3d189117bfad5d83c2ab99bb3e82b2eaaf5246bbc1

volume:
  storageClassName: truenas-ssd-nfs
  accessMode: ReadWriteMany

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists

externalDatabase:
  enabled: true
  hostname: mariadb
  port: 3306
  database: kuma
  existingSecret: mariadb-secrets
  existingSecretPasswordKey: MARIADB_PASSWORD
  existingSecretUsernameKey: MARIADB_USER
