image:
  repository: harbor.yanello.net/docker/louislam/uptime-kuma
  tag: 2.0.2@sha256:4c364ef96aaddac7ec4c85f5e5f31c3394d35f631381ccbbf93f18fd26ac7cba

volume:
  storageClassName: truenas-ssd-nfs
  accessMode: ReadWriteMany

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
