apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frigate-public
spec:
  commonName: frigate.yanello.net
  dnsNames:
  - "frigate.yanello.net"
  secretName: frigate-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io