apiVersion: v1
kind: Secret
metadata:
    name: frigate-secrets
    namespace: frigate
type: Opaque
stringData:
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:7hXlAngTINau/dm5,iv:oXk/mOWoRhbbmocN4NrBG7zy6bZFEUC2EfeQ5aBRys4=,tag:8BTixIo9ZBmwIsOC0u1Dfg==,type:str]
    PLUS_API_KEY: ENC[AES256_GCM,data:wUSKs9ZKH4ai0OJY7Z8qbjlSh5TYweWU+t0q0w0Y3HMRx5vwkztfnrXDW1mbCGqXGAeaxkToe0Tfm8H+xWEFzDB9dln0fLsTIA5CgJg=,iv:ITHwSvwjbF5ngOAD6sJM8dxbg7uqGEiJyCXxN6Lnhk4=,tag:Sjm1sFz2lmm6P3ksAn2npQ==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:ARnPclTYbCk6t8I=,iv:t4FgqzypRxBtscYkKI8icuAyLayXqAfJTAWJ36T+sl4=,tag:aiv2N8BLZObai3hZSETDzg==,type:str]
    FRIGATE_OPENAI_KEY: ENC[AES256_GCM,data:t9Sod0em8zcu1+9WUECLAxa8FqEfT5AxhYLkyA+FCfYuYwfs8dTlzfgaZenTcemmokegDl5++xa5L9Iw3iaRbCRorgAJX+Eb/w==,iv:tQGjTMSsEGNBBASPxcUxpD/ebhxD0HuaIBlCCSQFbz0=,tag:Z5kWPFQiB7QVy2v/uIvQPg==,type:str]
sops:
    age:
        - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
            ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
            WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
            NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
            +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T17:33:05Z"
    mac: ENC[AES256_GCM,data:zdyWx57Z7QQ2SrZklnRDnY+lbhSTh9FZ7cOAQuOlyuQGwPfhmlS3PpgEvgKBFLPqYCZYTmK7Nbx8jJfkKWZG5aGBG+7nJti+Jq9mj7sJG88nnfliJFBK8KyEiJnN2e+YdLYefHas1LyYUtaUEDirVyHkOtxRzIzEfeZEYta91sA=,iv:3fwdK5S3EIpsV2dRsI435SaR3yswkqlNdJLzbVFmQ0c=,tag:VMLLOKjGu6lNotfa4aO5wg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
