---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
spec:
  template:
    spec:
      containers:
        - name: frigate
          volumeMounts:
            - name: health-check-script
              mountPath: /usr/local/bin/health-check.py
              subPath: health-check.py
          livenessProbe: null
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
spec:
  template:
    spec:
      containers:
        - name: frigate
          volumeMounts:
            - name: health-check-script
              mountPath: /usr/local/bin/health-check.sh
              subPath: health-check.sh
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - /usr/local/bin/health-check.sh
            initialDelaySeconds: 180
            periodSeconds: 30
      volumes:
        - name: health-check-script
          configMap:
            name: frigate-health-check
            defaultMode: 0555
