apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Frigate
    gethomepage.dev/icon: frigate
    gethomepage.dev/description: "A complete and local NVR designed for Home Assistant with AI object detection."
    gethomepage.dev/pod-selector: app.kubernetes.io/name=frigate
  labels:
    app.kubernetes.io/instance: frigate-app
  name: frigate-httproute
  namespace: frigate
spec:
  parentRefs:
    - name: cilium-private-gateway
      namespace: cilium
      sectionName: argo-tls-passthrough
  hostnames:
    - frigate.yanello.net
  rules:
    - backendRefs:
        - name: frigate
          port: 5000
