apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bitwarden-sync
  name: bitwarden-sync
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: bitwarden-sync
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: bitwarden-sync
    spec:
      containers:
        - image: harbor.yanello.net/docker-hub-cache/reaper0x1/bitwarden-portal:latest
          imagePullPolicy: Always
          name: bitwarden-sync
          env:
            - name: CRON_SCHEDULE
              value: "0 0 * * *" # daily at noon
            - name: TZ
              value: "America/Chicago"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: ENABLE_PRUNING
              value: "true"
            - name: RETENTION_DAYS
              value: "0"
            - name: MIN_FILES
              value: "0"
          envFrom:
            - secretRef:
                name: bw-sync
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 500Mi
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      restartPolicy: Always
