apiVersion: v1
kind: Secret
metadata:
    name: bw-sync
    namespace: vaultwarden
type: Opaque
stringData:
    SOURCE_ACCOUNT: ENC[AES256_GCM,data:FQrVh9kUqIX8wSL7emT0BTgE,iv:RuXRQg2vjiRwaYPaa6mPtRr/70jbdFY4MCgAwDtmqfY=,tag:J4RqfUupJL6UfMgaM3DoUg==,type:str]
    SOURCE_PASSWORD: ENC[AES256_GCM,data:b39beH8epdvQCISDZPTx6g==,iv:AcuUZ63A1vbkCAyD3GP1tVX2OqoyaV4fJTMH8Cocnpk=,tag:J+CY8J8NOCKSkhOW+32n+g==,type:str]
    SOURCE_CLIENT_ID: ENC[AES256_GCM,data:4JIIr+1Poz5K+gSYWNX7BaqaCPzJ0D5Fd+14CnYabNACL706PffH6Aw=,iv:ly6lr0+teDKL7ibiHwFy/i6gd4IQEMefKCoVmQzvdTo=,tag:qUBe8ROuXu3BSvyg6SeHNg==,type:str]
    SOURCE_CLIENT_SECRET: ENC[AES256_GCM,data:z0fdlaK9AJzEQfcY0xYOAp0Rc3GNzFea/7M7Xau6,iv:qRUkdvuMm3kvly74TWM1J8ZrC7QjTuASg9GZqQvbUGc=,tag:J6cJp5KP2VvO+ovtNMtybw==,type:str]
    SOURCE_SERVER: ENC[AES256_GCM,data:XOlkzwnYSYFZ2VwgNwdDOVBtl4A7,iv:qis3u3e2PRedkZFjGhRda2q+wuYDHpXxC6MfZ5bZBXM=,tag:0mrwGhYLzxGHXpc8izJDdw==,type:str]
    DEST_ACCOUNT: ENC[AES256_GCM,data:0O5cq2Muw/BgmSh3+51GR/8i,iv:ZkV6hM5DuuteBrJadsKNy4fyxL0EYkxzT9TFIxBDCj8=,tag:1NBU800WPNnWzqudIrn9EA==,type:str]
    DEST_PASSWORD: ENC[AES256_GCM,data:2Pkw/RjNlkUlqJkheQbl,iv:HOkTZwBo4CRKUI5n53FYf5uTH35zqwgV0tFeCW5/ZIY=,tag:wK1H5Bla4jr2KddLTWX+2g==,type:str]
    DEST_CLIENT_ID: ENC[AES256_GCM,data:VLB5i9CoZgP0m6AvY2HW0uSSezRNBpDC38P9aJq8QmSkVUcnOBRln5s=,iv:66aBrFbpU1RI7CmRN0OCCxEqtv5iNQMFnQge/ylVK+Y=,tag:yGqwSnin3dSt8xqivOgfCg==,type:str]
    DEST_CLIENT_SECRET: ENC[AES256_GCM,data:wXwzZRtLj6MMQnR7B5Oes8xFS75kPmdzzcGjqWcG,iv:aocDAx4eNEGFKe3kXEGC953OTgDMlZ4lAhad0VySUqY=,tag:PKpTtUvCxaZ33w7UeSlpGw==,type:str]
    DEST_SERVER: ENC[AES256_GCM,data:IefhXT0hxhGxgqwrni3SfuA4lR+4,iv:mXTiFavo4jmXNpdeykvgGbeKH7y6HJ2tfjEwVOs7g1c=,tag:YN4PZEiXbFt2dbqvBqmLiA==,type:str]
    ENCRYPTION_PASSWORD: ENC[AES256_GCM,data:62XJkyclhZrMlm8Fn/kCJCvGXqZ9ti77crGpgX33daxIHNsb,iv:ubeNKXVoA/A9330N80/dCM/Y7nXQwzjdi8q5a8rS4+Q=,tag:z30msGavu5wXenQElOBReA==,type:str]
sops:
    age:
        - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
            ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
            WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
            NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
            +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T23:05:19Z"
    mac: ENC[AES256_GCM,data:D4OUGTjCphn9723y5dRZ4n2WoLyKVRThDNHx9fOl88Su/d0mMWS+Cc2WIsmnB3kRLhXhTV1zsBFH3UCz4dp+M8X9VwO5wIq3CUD4ClXISKP9tTpdoFuxUXTOH4duwao0BiUM00kHzPuveQ1UP3NERpv5gxPGWj17ptimSH+Fdw0=,iv:q9Em+bmPqiyjh1p7sQb12G7Yx7YrJM/C40NOrQLsisM=,tag:j4GI9v6wILcr7arWREt5mQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
