$ANSIBLE_VAULT;1.1;AES256
66663131666130386335623230636131356134333230396637353162303934613032666266373336
6630623562363334393936343761363865666431653934380a633737303537316338323531383738
31646561373666626462633232643037316434333665636533643837653561633636613732383364
3838343231353337660a656331363337663264653836313732333063633631313538333734643838
39386164306433613162356239353161313631376432303836356339626636616563
