---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./manifests/http-route.yaml
  - ./image-pull-secrets/app-set.yaml

generators:
  - ./manifests/secret-generator.yaml

helmCharts:
  - name: forgejo
    repo: oci://code.forgejo.org/forgejo-helm/forgejo
    version: "16.1.0"
    releaseName: forgejo
    namespace: forgejo
    valuesFile: ./manifests/values.yaml
