apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    namespace: nextcloud
type: Opaque
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:bwX2tVim64zaMSujZXkUlb/9zKnUxEJZJTNW8iiF2vGrpse8pkaqEYcyCJRjt6xglNdJUHlZBUpX1sW63/CScg==,iv:uI2THx1QrXHwVwgFesqHeoZrV0qSB7QakdEa76JtGRw=,tag:Be6hNITE2q1dmNexY8tU3Q==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:RPvjxazFUjaNGfsaOlsBbq2t/z4V61okAqj+PJsYBIZqhEouHKzXfcWtUoxJqAZeFslCliZBPgwq80TCF9LGvA==,iv:96B+HsIzo4k64oNieP34XoH+6WJ5P5ZV2A+vL4WAXMU=,tag:u6lefd6EV0QL7JdBgnxvZQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:45uJaNg=,iv:cahVK0JoYOU6YMT7WBUD95WlMKmKp0yKlJadLfthMus=,tag:zOAGTUPRVn8W1Les7B2QIQ==,type:str]
    db-username: ENC[AES256_GCM,data:Rh12i0+KXvQB,iv:C6Ipx4NVAMJEDKKcZOj0Xyo1iZR9HSMoS1+qxwdGxOE=,tag:yo5YPGbDtFf0J0YF4r0YLA==,type:str]
    s3-host: ENC[AES256_GCM,data:rTUA782hfgBn+sJyCxsQAqbA56PDKgQfAPcDHO7g,iv:DXR8wOFVnRPjmh8JUd90RZvvrWddNMbxh52iY7AtnYc=,tag:fJXT/htqHD7wlWqFSXswaw==,type:str]
    s3-access-key: ENC[AES256_GCM,data:mGhHHCWrrBIB8S4UcKYh3BQ+djVk/e+Ixg==,iv:HbB661EhxhTH/BMBr/tikXvqkWuQoRvrAgn+LGYVeHc=,tag:n8JVq9TZ/zgUEKkFAMPgvA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:scdqkz4eAOOA27Xe+AwC0p7rnLg7qeQIH1vLleavXg==,iv:NOItJqFLSmSpIOFzSWjiec22HIMhKn2BrxSZZI+k6FI=,tag:UOQYBKb4FabctoYoMs8OxQ==,type:str]
    s3-bucket: ENC[AES256_GCM,data:jeqoCdmEymsHEONFrfjDRnoZ,iv:6/stjYNLiek3iR9friZyYq+hV8zC2nvDcG0nLEf5/eI=,tag:XSZR4nfMIc214XOko4Lr9Q==,type:str]
    NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:GbvF4FnB,iv:YYPkPVs5jr0s5/sE4nFBR0Uo6fwR0JXY2JFMKGBaU0U=,tag:9wbh2Z6pdLH1ybNxCthvnQ==,type:str]
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:5uQw25o9j0RkK7NI,iv:xPkVskBpv8D+Mr00ZzTrbBCB1f7/VvgN8bmu0y5qGqM=,tag:pwEwkOObJHXjTUxOfmXYnw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:IxD8Wdsf+nDDBMw+4/e6+w==,iv:/6pKtS8mZUCWsPV1A1ipRqsMFfRliZp0Ke8BIKdeVQI=,tag:mt7Ks0McIy1/vXXnVz2gGg==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:QuhGzO7Z6Gb1geLLIyc=,iv:fHMM8JcjBgix6Zsd+UzJyrLKuoRzASfoz/IX4ErRdJc=,tag:IWjnlmo5YfF7PIGqh0kmlQ==,type:str]
    SMTP_NAME: ENC[AES256_GCM,data:fAXahhTnOVK9Rl8rD0s=,iv:+FtR4mfQcFlGslcOXnfN74Qgci5/F/HVDqa73Fls6Mk=,tag:queZhfF2Jlvu81uVa+5GKA==,type:str]
sops:
    age:
        - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
            ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
            WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
            NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
            +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T18:06:04Z"
    mac: ENC[AES256_GCM,data:HXFtHZMpiX7VvTOBQtnopoIB+VhOg6/vWxfgmtjQsG6qcw/Nb2F0IBRfYjmN72LL40mGECpyC6F7n6XXtqRTeviMC4Wqd3KRHVy/QPRO/XRLa+V/BZpmixB8jLFp+JESsxK88rPeGYTVTqTlW6O6bKT232kjt/8OppAMmiAawkU=,iv:4psIOJiQx1SOrtxNaOrhYKGob4VcL3dyFcq3nzM08Vg=,tag:5KQuwB7E6LmAFJ/MOefUFw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
