apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./manifests/http-route.yaml
  - ./manifests/longhorn-xfs-sc.yaml
  - ./manifests/recurringJob.yaml
  
generators:
  - ./manifests/secret-generator.yaml

helmCharts:
    - name: longhorn
      namespace: longhorn-system
      releaseName: longhorn
      repo: https://charts.longhorn.io
      version: "1.11.0"
      valuesFile: ./manifests/values.yaml