apiVersion: v1
kind: Secret
metadata:
    name: resume-secrets
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:Ng4ch3oY9Ng=,iv:nhNpN1rQiVGtsX3q4wce3+EdQGEm3CSHJiNOt6Csgtw=,tag:ChWbbFSwy69DB2urbjZIYA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:K9/YJbPQaHW6ElV4jQII4uM6EMeYLLY3lzgNhLA0gL9JAgpMM4I4XXEOm9u+xTMD9fdcrUg=,iv:KPMdWY6iqlbWokNCtmu4b3qXxZ/WKjfswRxIXVq7WhU=,tag:BPcmCeYQtK7t+IvZGNAO8g==,type:str]
    STORAGE_ACCESS_KEY: ENC[AES256_GCM,data:GgpMRc7s9PTY6BCKC0nKfKx+GWZi+h8/KQ==,iv:jHyyjh0oBYoVQqR99qrxQRhK6v8x1C1P2OwrC1Q/ACs=,tag:ctrofpGhYwLlNi0f+bYojA==,type:str]
    STORAGE_SECRET_KEY: ENC[AES256_GCM,data:g4CTgfMe5vp8NV96Bm3EowCoci8liWGr9DVMyJiEmg==,iv:SXW5pF0R/vx1HSK1PmWz1OrCGysOBH06elWFP1H56Jg=,tag:HH4UM1DUEAtgmU08qUJBMg==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:0DJJYBFiDSUvoY4qKbd/QLH1L0MXv3Xu+lqYS4lYPsWX5Y5+Z88rCQ==,iv:L284IREwU+Wc1OfHCSbI/UT7WYNRUc5gXMmNLHdRIz8=,tag:PTC/5ZQCT9Lc3E+aYo9NVA==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:7gPjYf9nShF43dknfUtOFEPl65/STcdZ+wpUS5HQQ5twjQNGkGqQ7dhm1iw64og1IVsGdWwgXWIfCpuhS3a83uti3Kws9QcZ7Vdd2EdLRQw2QulkD0AyMFjXKK8fsm5TPIMn48iY77Z2bY1T8nsPOY+DSAbQpE5d+Y27KM22FkQ=,iv:Zt2ItdmrVtBYovahxKGeCfe5Nlkhn6xyxbe473ZVVLM=,tag:6O2XW4tzFJonCm+YXaYQvw==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:AZiDwg78EgBSgQffiY4Cz2AWxMV8o/uNNVQw4XU9HU+birNd,iv:/BgluGPc2dXrW4dvrfhy3Uw9cva4WcyOBEP6LLUEGLk=,tag:jiQwIsPd9hnnundOsIHMWQ==,type:str]
sops:
    age:
        - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
            ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
            WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
            NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
            +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T00:07:23Z"
    mac: ENC[AES256_GCM,data:hMiaQ1qMaEpOXLgbZSYBGRIlUEiTh2x7DVds1VYX8XyXpIVNnNAoIDzY7+T0lXWgQBBSGLjva4Gnt5LVTd2wk+U9LPmvEyq708ErlXy5foZjS5ogxBOsfSSfo2fCVOWa4UGd0qZ2rkkbQQcCDBV++yO8tzq9WxUNS2K30r7uK5k=,iv:CWXioFgYZ/xgJW3xFwsJrbfhQpRx5eYjlydnzbb1JC4=,tag:elUM5xA732X8ZlEhfvQR5A==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
