apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:xNm3XwQ8jHpdSRdnf/p8NaquurxsoNbRJptZ1QGWY9Sn/A+yt5upIg==,iv:x0boH9XCaUH2NjPV2x+LQ29XxkVcyDzpo99FsYRiFmc=,tag:SJ75d7R2p3UJhBvkLoAbGw==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:Z+wIpryUk0oeVjAyOLKNnFfe+zVG7CBDc3DY7BLZQEOHW5oGTnnseg==,iv:XOrOiUVDGEO1Q1tBkWbnV93w9LUHm/88cMCEEkWUPCk=,tag:tn4yeUl4SYsZ6H3SVkFtsg==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:e57b/mVxTkvTfEjatK2ZcBIT4CdKFRAVlKSakr1ZblUvbCW6ZYtAuQ==,iv:PcBAlJS3vuqBlOdmhDpvUJ27e9jL/RwFXjbldpuQVRQ=,tag:TO6AUiCOGvE7P0BpnSu2sA==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:Hx6ecYg9GyJqajmWy1eYnydQKSuZ0SjjBv/Ez5/Csrv6qS0jxaKczDNGL+7DWZLmyJZjuRnTFV70BmW8ufCciKgJhrmXTpIjIQG1JYYP0rg9++87IbcaTu8/VstuK4Y9commr0IZN5GOPqUxX+NQ48acrKp80/RZHAQA5Dn8yJS+evBgf2V/VRP8tQHFwtLV5182UhggS88utMEh8glfYpL6MgxTRSmgg4DP7jxiERWAW6qB9sd5RkCqj0GoLihyFHaAUcOQ8uPJtGbG7wXRttNCL+xtSZ/EVPaz5K1lLInpy10k+oIdSq+6SXkpE62WJMj20pcHa76kTkxjN/DA873ZqfVU6Abd42uK7Km6ED7HLqkB1vFgbmRRYEyRn2/UK8ZZX0AWlil8k8d8aYJs1KAnDkeA+wMpKm8FOijLlPcBlh0x8l9+4v11F6TE6TETgZpDgC25Wz3lj5hcXzJqIy/y5Q6KpuGwp0Uw+tlNeqDHXmsvLeSs+dlgiOpPvYPNGHFbhVee4kKdB5DS1rJ5JhVlJqzDpEVDYvj2xw==,iv:Hzc5vap6aAeORwRI8a79h1UG85lYXVTsOmiS914gHcc=,tag:4isPn6b7Ex9DUXXUivyvlg==,type:str]
sops:
    age:
        - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
            ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
            WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
            NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
            +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T16:31:14Z"
    mac: ENC[AES256_GCM,data:WBJqkFtZjZNeC6YbrGCBvr1DYE4cac6cnRU/fIgYd7AfBm/h+EmEJqoSGvSH4Fir3zT8ZU2uWQkC73QE6zrF4blspofoey6ovWWvk+jmyUCLm+d0NrlkZMDl3UiZzICTT0c4WZqNsajmlqvduahtksNyx7iJDZziOlPNrJtD67A=,iv:1fBMXAXkMdy4O6qPQaTTZdB2SQgTToZZp5r2xTeX+PM=,tag:T6V/jK8T0ofA/2RN1cRdkw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: ai-secrets
type: Opaque
stringData:
    CUSTOM_API_KEY: ENC[AES256_GCM,data:ycVsVPKQO33bPJL/rV1IZUC0HPN5IynL5897sj0C7ixRwkZLqpQQR7WoUFTP9w3edyWje9Pm0EmuimzflTplfrjCRGnl4uerng==,iv:fRccJy/MJBRvuxKvhiXPo5CrkIZkjLmjTVAtXtoKN2M=,tag:yd9hW5irExNy4qPOwbrTPQ==,type:str]
    PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:DN9wiyA1mEoQRN8AetUBGJMod/H43PYwDrEIWUNCma4g4dOsCzrOcw==,iv:EFN/RsJOienuSIFmMTqeWqx804vve5vdv4QlfDhh1K4=,tag:CSfyA9WFtaIx5QOh1CnWsQ==,type:str]
    PAPERLESS_USERNAME: ENC[AES256_GCM,data:tcwXgHL/,iv:zn9BhjQkF1ZGG3hPcLTyDC+ZJC52ppgJYA4DggOj4zM=,tag:+Nariac8WsRZwJFVcvo+9A==,type:str]
sops:
    age:
        - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
            ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
            WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
            NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
            +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T16:31:14Z"
    mac: ENC[AES256_GCM,data:WBJqkFtZjZNeC6YbrGCBvr1DYE4cac6cnRU/fIgYd7AfBm/h+EmEJqoSGvSH4Fir3zT8ZU2uWQkC73QE6zrF4blspofoey6ovWWvk+jmyUCLm+d0NrlkZMDl3UiZzICTT0c4WZqNsajmlqvduahtksNyx7iJDZziOlPNrJtD67A=,iv:1fBMXAXkMdy4O6qPQaTTZdB2SQgTToZZp5r2xTeX+PM=,tag:T6V/jK8T0ofA/2RN1cRdkw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
