apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./manifests/httpRoute.yaml

helmCharts:
  - name: victoria-logs-single 
    releaseName: victoria-logs-single 
    namespace: monitoring
    repo: https://victoriametrics.github.io/helm-charts/
    version: "0.11.22"
    valuesFile: values.yaml