---
apiVersion: v1
kind: Secret
metadata:
  name: provider-secrets
type: Opaque
stringData:
  cloudflareAPIKey: ENC[AES256_GCM,data:AKAqyZ9LgFhQmuk5FDHKz4Dqlf2S6IZ4lKSyK5LAJZTUJGfZTyb6ew==,iv:F/2T9w3cRYAIg6GyfBD06UpYpx6hrtWoHnfUmWag8dA=,tag:0Yqz/5QQIFTyGWiEAnLOLw==,type:str]
sops:
  age:
    - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T15:38:51Z"
  mac: ENC[AES256_GCM,data:U+gTWg4zfuK9lcbizat2f2wkWusaSzLBtDzuQTyUDBSyUIp4pnPN12u8MC8JmmUns9DbRdKhNGu4r7onanhkrP3o+kdhusth4ff3RkqbxPC8k6nYZbwOy8ZhZCz3yzjQ/3rNGTrXuLiZzZYRQoCGvRftEjcKCUQee+ofO4TSb0I=,iv:CsE9EK4Hh5KwVYlNLTuAt0X22O6AcNNzBCHpUExuaNw=,tag:/9q9e3cUfn5wqmyeqLP2mw==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.11.0
