apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: iocaine
spec:
  scrape_interval: 60s
  staticConfigs:
  - targets:
    - metrics.iocaine.svc.cluster.local:42042
  path: /metrics
  scheme: http
