apiVersion: v1
kind: Service
metadata:
  labels:
    app: iocaine
  name: iocaine
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: iocaine
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: iocaine
  name: metrics
spec:
  ports:
    - name: metrics
      port: 42042
      targetPort: 42042
  selector:
    app: iocaine
