apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: vllm
    repo: https://vllm-project.github.io/production-stack
    version: 0.1.9
    releaseName: vllm
    namespace: vllm
