apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./manifests/http-route.yaml

# helmCharts:
#     - name: jellyfin
#       repo: https://jellyfin.github.io/jellyfin-helm
#       version: "2.3.0"
#       releaseName: jellyfin
#       namespace: jellyfin
#       valuesFile: values.yaml
