---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-secrets
type: Opaque
stringData:
  key: ENC[AES256_GCM,data:xQmsuDU6ox/WRkB0njqs9DJDzbYYr63zKk1h5sj5rHDWESsRi0wqeA==,iv:YiTbqULZcVr+5uOHG4EOa7O+qeMsCiAoBx2wlZ1vC/A=,tag:1gEw2AY7QBJiQKFex3zWfw==,type:str]
  secret: ENC[AES256_GCM,data:zx+b9Y5H2qtqVakxrN+6L+O3LVUBMPF8re2oYbggZ/+U/zTuRHSCwWD+N1swPJvwzo05Xo0oW0csXYja6iiC4eMu4M1i6e04urcujJ+h1ZNCCz1RcNyx4HlXqsicB5gzNEypRkXd8/xkOdV0Nmf8xEC/pUSAFErAi62sTdAd4qQ=,iv:2Cel/wy5vZZpk5swfaV1ESdZhQC2KwVY3s8uzvUM9Vk=,tag:bN6cKePDx9Y1NTlFHCn4Zg==,type:str]
  username: ENC[AES256_GCM,data:NTehFLDOfRSgqT8=,iv:P1Zv/FgIss0pWCOwpcN88TyLUSDu/mzJyaP53vf3w5c=,tag:zsf3V8TYEybk3cIpVjvf0g==,type:str]
  password: ENC[AES256_GCM,data:ziulzFW1F6uXpl3orTOi,iv:RlUlP/x4cK+kQe2enV2I4QxAV6DD+M1luWJoYcHJ1ig=,tag:MTecTmnmtWguTE9TBecsAQ==,type:str]
  user_db_password: ENC[AES256_GCM,data:5LrkmODW9LIa6Aa17UP5HdT9mm7fiTsts5UvfnpDFMkmWfDq,iv:A2URTrrjFvlv5R8I+Kpgciq1Bx/XjctQdxnQl2cE+UQ=,tag:TTFCDuyopoUKrs+yvjlXyg==,type:str]
  admin_db_password: ENC[AES256_GCM,data:WWrJk9r6rbZsGk1WQDSkUn2qhqsKbenHhoM4OsWsI56+eeeC,iv:WFdJOzbKddiXsREQqL+fX/A/JgLK0tK+H+3y2Sx+Vjw=,tag:3QEqcMNqNTiHnRESUclvDw==,type:str]
sops:
  age:
    - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-13T03:11:50Z"
  mac: ENC[AES256_GCM,data:qeo7a8+UwEvjwwHH4/gHSerqhs/xq8y0pJGI9uHPQ3fLwakpvMp/F4hKSHSSOUU4GL+OLMLFujMPBsf4cLRA8XbbpDaPqLS8t4LRA59dF9KD1aGg3Vn1PzGuyMSM8lBQfZeI3LsjDwxq8ioPiLSaE5yWirXwHfMvd02fZTOVtak=,iv:gqS9tRHnU4UzBW+JnzcAWspOaPY4jfvVUKdX9ozgCeQ=,tag:OtsydPUXMWOUkuBg7XDZbA==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.11.0
