---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbbr
  labels:
    app: rustdesk-hbbr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustdesk-hbbr
  template:
    metadata:
      labels:
        app: rustdesk-hbbr
    spec:
      containers:
      - name: hbbr
        image: harbor.yanello.net/docker/rustdesk/rustdesk-server:latest
        command: ["hbbr"]
        volumeMounts:
        - name: rustdesk-data
          mountPath: /root
        ports:
        - containerPort: 21117
          protocol: TCP
        - containerPort: 21119
          protocol: TCP
      volumes:
      - name: rustdesk-data
        persistentVolumeClaim:
          claimName: rustdesk-data
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbbs
  labels:
    app: rustdesk-hbbs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustdesk-hbbs
  template:
    metadata:
      labels:
        app: rustdesk-hbbs
    spec:
      containers:
      - name: hbbs
        image: harbor.yanello.net/docker/rustdesk/rustdesk-server:latest
        command: ["hbbs"]
        volumeMounts:
        - name: rustdesk-data
          mountPath: /root
        ports:
        - containerPort: 21115
          protocol: TCP
        - containerPort: 21116
          protocol: TCP
        - containerPort: 21116
          protocol: UDP
        - containerPort: 21118
          protocol: TCP
      volumes:
      - name: rustdesk-data
        persistentVolumeClaim:
          claimName: rustdesk-data
      restartPolicy: Always