---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbbr
  labels:
    app: rustdesk-hbbr
    app.kubernetes.io/name: rustdesk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustdesk-hbbr
  template:
    metadata:
      labels:
        app: rustdesk-hbbr
        app.kubernetes.io/name: rustdesk
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: hbbr
          image: harbor.yanello.net/docker/rustdesk/rustdesk-server:1.4.5-amd64@sha256:dd0c6ed388399840f1cf48848b6fb802f2ebc9400fea444967fb2562eaa938a1
          command: ["hbbr"]
          volumeMounts:
            - name: rustdesk-data
              mountPath: /root
          ports:
            - containerPort: 21117
              protocol: TCP
            - containerPort: 21119
              protocol: TCP
      volumes:
        - name: rustdesk-data
          persistentVolumeClaim:
            claimName: rustdesk-data
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbbs
  labels:
    app: rustdesk-hbbs
    app.kubernetes.io/name: rustdesk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustdesk-hbbs
  template:
    metadata:
      labels:
        app: rustdesk-hbbs
        app.kubernetes.io/name: rustdesk
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: hbbs
          image: harbor.yanello.net/docker/rustdesk/rustdesk-server:1.4.5-amd64@sha256:dd0c6ed388399840f1cf48848b6fb802f2ebc9400fea444967fb2562eaa938a1
          command: ["hbbs"]
          volumeMounts:
            - name: rustdesk-data
              mountPath: /root
          ports:
            - containerPort: 21115
              protocol: TCP
            - containerPort: 21116
              protocol: TCP
            - containerPort: 21116
              protocol: UDP
            - containerPort: 21118
              protocol: TCP
      volumes:
        - name: rustdesk-data
          persistentVolumeClaim:
            claimName: rustdesk-data
      restartPolicy: Always
