---
apiVersion: v1
kind: Service
metadata:
  name: rustdesk-service
  annotations:
    lbipam.cilium.io/ips: 10.10.8.50
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: rustdesk
  ports:
    # hbbs
    - name: tcp-21115
      port: 21115
      targetPort: 21115
      protocol: TCP
    - name: tcp-21116
      port: 21116
      targetPort: 21116
      protocol: TCP
    - name: udp-21116
      port: 21116
      targetPort: 21116
      protocol: UDP
    - name: tcp-21118
      port: 21118
      targetPort: 21118
      protocol: TCP
    # hbbr
    - name: tcp-21117
      port: 21117
      targetPort: 21117
      protocol: TCP
    - name: tcp-21119
      port: 21119
      targetPort: 21119
      protocol: TCP
