apiVersion: v1
kind: Secret
metadata:
    name: s3-secrets
type: Opaque
stringData:
    AWS_ENDPOINTS: ENC[AES256_GCM,data:Ze8oQ47phBHCxGI3P+6j7dH7fd8tONmbwjsX5me6nW9F8cJWcqo=,iv:KRhgM2tjdY9uMaSaw1001NwLwCUlZ/6H7joVHCryU4g=,tag:iFTPuSRNdlW6deEJttUPfA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Byyy8T3BO5N56rz6xc6riNJod6Gw4yVyQw==,iv:SUCmpuD7llBiMI9L4Vtewm34BwmnbsC6AsUHAlVtQ8s=,tag:zq0d1IfHgjGJglyLItJv2A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:7e3fN+uJYk8FTpVYjMntrk36ZwOCjGVcwlO+GLJQOQ==,iv:BSys/pVRf4Oj/DJG470fOdrESuCdt7A6dKdgCDmGNVA=,tag:Wq4uoXx1FLfKX1bZKYxPCA==,type:str]
    KEY_NAME: ENC[AES256_GCM,data:RzWvpnH9WOk=,iv:1OEC/UIZx/lGErw3sN9zb1KQZDA7Ay/ezzDP0wGyzyU=,tag:4R88qWk+cVP4h92oi3Ajrw==,type:str]
sops:
    age:
        - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
            ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
            WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
            NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
            +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T15:09:37Z"
    mac: ENC[AES256_GCM,data:evVO2XRmlGQ1XPuKZXr9Kojq2FprePfnhP7sSepgQKxC0vlLEC3bNfpEclVk7KhZ7fsax6RJaviKRfKyCy0ebqA1oKuFFj9IFSmsGPw3z1AiVC0w38Nyvjj4496T8t26ccBINPQlzwnw7oKX+GzXxzLFLZ40mVl2aDGI4sQSrrE=,iv:hWR6HwDJUYXcV2+BXrfsaMo251wpnFmNIwrC0c4raGA=,tag:+Vve765UWjYJsS7htwZjZg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
