defaultSettings:
  defaultDataPath: "/app/longhorn/"
  defaultReplicaCount: "2"
  taintToleration: "node-role.kubernetes.io/control-plane:NoSchedule"

defaultBackupStore:
  backupTarget: "s3://myanello-longhorn@s3.us-west-004/"
  backupTargetCredentialSecret: "s3-secrets"

preUpgradeChecker:
  jobEnabled: false

persistence:
  defaultClassReplicaCount: "2"

global:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "csp/oci"
      operator: "Exists"
      effect: "NoSchedule"
