apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photo-frame
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-hdd-nfs
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-hdd-nfs
  resources:
    requests:
      storage: 256Gi
