apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
helmCharts:
  - name: eck-operator
    repo: https://helm.elastic.co
    version: "3.1.0"
    releaseName: eck-operator
    namespace: monitoring
