apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fooocus
  labels:
    app.kubernetes.io/name: fooocus
spec:
  serviceName: fooocus
  revisionHistoryLimit: 3
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: fooocus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fooocus
    spec:
      runtimeClassName: nvidia
      containers:
        - name: fooocus
          image: "ghcr.io/lllyasviel/fooocus:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: CMDARGS
              value: "--listen"
            - name: DATADIR
              value: "/content/data"
            - name: config_path
              value: "/content/data/config.txt"
            - name: config_example_path
              value: "/content/data/config_modification_tutorial.txt"
            - name: path_checkpoints
              value: "/content/data/models/checkpoints/"
            - name: path_loras
              value: "/content/data/models/loras/"
            - name: path_embeddings
              value: "/content/data/models/embeddings/"
            - name: path_vae_approx
              value: "/content/data/models/vae_approx/"
            - name: path_upscale_models
              value: "/content/data/models/upscale_models/"
            - name: path_inpaint
              value: "/content/data/models/inpaint/"
            - name: path_controlnet
              value: "/content/data/models/controlnet/"
            - name: path_clip_vision
              value: "/content/data/models/clip_vision/"
            - name: path_fooocus_expansion
              value: "/content/data/models/prompt_expansion/fooocus_expansion/"
            - name: path_outputs
              value: "/content/app/outputs/"
          ports:
            - name: http
              containerPort: 7865
              protocol: TCP
          resources:
            requests:
              memory: 8Gi
              nvidia.com/gpu: "1"
              cpu: 50m
            limits:
              memory: 24Gi
              nvidia.com/gpu: "1"
              cpu: "4"
          readinessProbe:
            tcpSocket:
              port: 7865
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 7865
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - mountPath: /content/data
              name: data
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
