apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bashrc-config-test
  namespace: argocd
spec:
  destination:
    namespace: tenant-slurm
    name: in-cluster
  project: default
  sources:
    - path: argocd/dev/bashrc/bashrc
      repoURL: https://github.com/myanello/homelab.git
      targetRevision: main
      kustomize: {}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - Validate=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - Prune=true
