apiVersion: v1
kind: Secret
metadata:
    name: mariadb-secrets
type: Opaque
stringData:
    MARIADB_PASSWORD: ENC[AES256_GCM,data:jcd0OUYqVQkwAarmfchar7AuSCKOFKVYTuRZj5jtmh1I9kod,iv:z2bMKF8ba1+YWlSK1gwLscLJXT8csMrkmVL4eVQDgF0=,tag:iSqcCHmU2zptrgirXv2iyg==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:jz9esMKdYsLmN8Lbiya7PgXTaTme8kGhvn511hd7XcMyb1kllA==,iv:O5QqEeJTCmDAr7ZtynS+1bbw2tXgrf3KfT3OjkU/8y0=,tag:XBQeUNzAxDVYjlWH6olBXw==,type:str]
    MARIADB_USER: ENC[AES256_GCM,data:k40VcQ==,iv:ZzfRTqd4+MOaujdUmsHNEk9M+72EdVcYoH9PpPPDio8=,tag:NC7uTgIDRTmzDmu6I3VxTA==,type:str]
sops:
    age:
        - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
            ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
            WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
            NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
            +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T14:38:01Z"
    mac: ENC[AES256_GCM,data:yPuc1QDDsdgmLXhFYEeq5ZqkxJUePUfKOzHWV3z888ZnlPKBdum0V5911rpYoMyyCXpPJQZ2tIIivhscmUwvH5BIJtFQZeO/CccGVL/EQkU0hf0+8s58HzjrloVYW/rh6SgIlTjQc5DoDzXnzcL5d1+PCPeKJSTBzDAQZbkeSXM=,iv:c/ARXZ8ik8AH6lYwPxo9+iRq1uZONA2xO2vmAsihMCE=,tag:/LDENlIzpam9tCAf9HdELg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
