apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - ./secret-generator.yaml

resources:
  - ./http-route.yaml

helmCharts:
  - name: argo-workflows
    namespace: argo-workflows
    releaseName: argo-workflows
    repo: https://argoproj.github.io/argo-helm
    version: "0.46.2"
    valuesInline:
      crds:
        full: true
      controller:
        image:
          registry: harbor.yanello.net/quay
          repository: argoproj/workflow-controller
          tag: ""
      authModes:
        - sso
      server:
        image:
          registry: harbor.yanello.net/quay
          repository: argoproj/argocli
          tag: ""
        sso:
          enabled: true
          issuer: "https://authentik.yanello.net/application/o/argo-workflows/"
          redirectUrl: "https://workflows.yanello.net/oauth2/callback"
          scopes:
            - openid
            - profile
            - email
          
          
