apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - ./secret-generator.yaml

resources:
  - ./http-route.yaml

helmCharts:
  - name: argo-workflows
    namespace: argo-workflows
    releaseName: argo-workflows
    repo: https://argoproj.github.io/argo-helm
    version: "0.47.1"
    valuesInline:
      crds:
        full: true
      controller:
        image:
          registry: harbor.yanello.net/quay
          repository: argoproj/workflow-controller
          tag: ""
      server:
        image:
          registry: harbor.yanello.net/quay
          repository: argoproj/argocli
          tag: ""
        authModes:
          - sso
        sso:
          enabled: true
          rbac:
            enabled: false
          issuer: "https://authentik.yanello.net/application/o/argo-workflows/"
          clientId:
            name: argo-server-sso
            key: client-id
          clientSecret:
            name: argo-server-sso
            key: client-secret
          redirectUrl: "https://workflows.yanello.net/oauth2/callback"
          scopes:
            - openid
            - profile
            - email
