---
apiVersion: v1
kind: Secret
metadata:
  name: provider-secrets
type: Opaque
stringData:
  adguardUser: ENC[AES256_GCM,data:rTCWQEeB,iv:8VRH3QlntTggju6t0rfm3A1JYmyZlPOehbTGEKYO1Bw=,tag:bBwvEi8affgvlDoh21mbHw==,type:str]
  adguardPassword: ENC[AES256_GCM,data:IuZ8wdBlONiCLTkHaog=,iv:3sJXjopBS8zVfjSnW10K08C/7FRd/hn4O+BGMsD7x60=,tag:Lei7H/hcz/vSsjAXzE524Q==,type:str]
  adguardURL: ENC[AES256_GCM,data:rpA1mR7tn89rOKrJYPJF,iv:hDRNuZHT1DsCczP8OnBPSWRWnNr7EQHkU/QWTxiwBBo=,tag:jsuBECs9EBrF0QTCOzzM0g==,type:str]
sops:
  age:
    - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T15:39:39Z"
  mac: ENC[AES256_GCM,data:zdWGMq4XCkmtYE+PoBy1QWwj5VPUSvuNvXi08s0vL6DJyet/ap44+q6D2Zv93CFEc7J4qo8InGypxamSR2r4hGL3mVIfu9Q+SPra+7bcGJJCsj6XX3qiwc2eZpRcXvs/MSUf8q5HPLOrBbAi+ikFG4VA3ioRxFd0R6k03CxmgXg=,iv:nX1KZfz6Fzk3ejLsJmrQzu+dIn54lCkNtdrF4okNfc8=,tag:qDeMrKmFakr7mLfl14C+Nw==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.11.0
