---
apiVersion: v1
kind: Secret
metadata:
  name: provider-secrets
type: Opaque
stringData:
  adguardUser: ENC[AES256_GCM,data:rTCWQEeB,iv:8VRH3QlntTggju6t0rfm3A1JYmyZlPOehbTGEKYO1Bw=,tag:bBwvEi8affgvlDoh21mbHw==,type:str]
  adguardPassword: ENC[AES256_GCM,data:IuZ8wdBlONiCLTkHaog=,iv:3sJXjopBS8zVfjSnW10K08C/7FRd/hn4O+BGMsD7x60=,tag:Lei7H/hcz/vSsjAXzE524Q==,type:str]
  adguardURL: ENC[AES256_GCM,data:U2YPR4PG3OOO4zCAecgnxPavYBSh4P8=,iv:dNSnHbjGb33xZ74BXpIJg8r0Df2csMvpj8j5UbPICBo=,tag:PpCV6LIBtZm5bO1NpQbfpw==,type:str]
sops:
  age:
    - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T15:43:00Z"
  mac: ENC[AES256_GCM,data:zo4lFqeGTBNjItmATz8GNi/deOPMQcUjs7R5FCMWByMrMZBaxVbSb07YqnQQvEBjlpKwFeNQyObWjvjfnlz2OV/Vy8FlH7BS2P2j/o+wJvZb1boF2G8RWEABUI/vs8BCgC7bhe6cVhcy+a3DlBC6yd5pewxUIykrZL8Ua3PUp/c=,iv:KJ6W3fhbI+x7wvQydpHN4iQrWYBNs7WT6rfbprtKknI=,tag:eSaQwGULX3xPFj4xo2xaBQ==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.11.0
