apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/instance: bentopdf-app
  name: bentopdf-http-route
spec:
  parentRefs:
    - name: cilium-private-gateway
      namespace: cilium
      sectionName: https
  hostnames:
    - pdf.yanello.net
  rules:
    - backendRefs:
        - name: bentopdf
          port: 8080
