apiVersion: batch/v1
kind: CronJob
metadata:
  name: kometa
  labels:
    app: kometa
spec:
  schedule: "0 */6 * * *" # every 6h
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            app: kometa
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - marcus-server
          restartPolicy: OnFailure
          initContainers:
            - name: copy-config
              image: harbor.yanello.net/docker/busybox:1.37
              command: ["sh", "-c", "cp -r /tmp/* /config/"]
              volumeMounts:
                - name: config-kometa
                  mountPath: /tmp/config.yml
                  subPath: config.yml
                - name: config-movies
                  mountPath: /tmp/Movies
                - name: config-tv
                  mountPath: /tmp/TV
                - name: config
                  mountPath: /config
          containers:
            - name: kometa
              image: harbor.yanello.net/docker/kometateam/kometa:v2.2.2@sha256:32992226d1a505da3ed5d4e9c97bed8a6deb7aef36cd5ef8b1f519762607df45
              imagePullPolicy: Always
              command: ["python", "kometa.py", "-r"]
              env:
                - name: TZ
                  value: "UTC"
              envFrom:
                - secretRef:
                    name: kometa-secrets
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: media
                  mountPath: /data/media
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "200m"
                limits:
                  memory: "1Gi"
          volumes:
            - name: config
              persistentVolumeClaim:
                claimName: config
            - name: config-kometa
              configMap:
                name: config-kometa
            - name: config-movies
              configMap:
                name: config-movies
            - name: config-tv
              configMap:
                name: config-tv
            - name: media
              hostPath:
                path: /data/media
