---
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-pull-secrets
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:zHUV9HRX6RNo119FrW7F+ukSa1ojHK8/GedeNv+Ty5szruDVTMCnJf4QRfqlxnkTCLXtQ8Rl6To1PxIMCHCESgKFA7AzVtURWjQufRP0Bsr7urd2HExeyt5jWz+3S5K6IHtX2E5xaqdP+vvO+1qwHfcR5uD73l0AqfmVzC4sPFughwGGJhTv05NX/Gylsw0qHsVrovV6oEX4GMtN9acL0sm8cb7gxIZRsQhOWIVjBb8EHzCbiDz0QsnoMipByGKyT7KlMFbqknZLoSU9yn2gc4EKcTM/J4QTDekr3RDEgKsoAC/XLp997L06lvh/V8pyHDejUoBfROL4RIXAfUGVSSMTtaewpM9tK11nSlkUmqrjL21DJiJyeGRg62wOSLjtc/+JEUm/965iMGtLKTneUP0RuVsJ/r4aowtJUg==,iv:MnR4+oMa45GF+xRgbj/sY3FQGv89zc722OmYyt3280A=,tag:6/PBdlrNwpwlKd0rR0ev8w==,type:str]
sops:
  age:
    - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-13T13:29:10Z"
  mac: ENC[AES256_GCM,data:yJBwsGTP/8BtEItdK4L32qQADff9hysOAiSqzyr2jV5P4R/A8/mAIxMQLcnMx/iyzvyv8a8Xfp8+w7jzWLaOJU0c7TTpA13fBwMSF35jNVn4bGhO5mgltCpR9kQ0SYIsQhxBgYCZhCAOYkYSWjVmznn5ddG20drTYTImktOFxaU=,iv:FnJ1H/uaqi1QI3kQyXeWkl5423GD6eHUz3r5N4QP9Tw=,tag:J3Yr6X9oSZYiOtFh2s4p1g==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.11.0
