---
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-secrets
type: Opaque
stringData:
  key: ENC[AES256_GCM,data:hmZt5yfsY/jXwaZIwfo8KfOU3dQxZ2XMSjwA9xy3sCw7Oyj2QerJyw==,iv:qrfZ6ey6K/sWDs8GnbWQj0kuBwONUwb0jOhQQfK71Ys=,tag:3mWsJB8JubWl3A9+5m8kuQ==,type:str]
  secret: ENC[AES256_GCM,data:K3VOwGhCZtLjOjKykonX7DGJEyC+rMjD+zQmzpcLJdS6NJ9pQoshZRdzGEgr3i+FyFlIVX4+mNKKEms6wyqNQHlSYnQl69KTDgZA4iRZvO52WKApcuo/YBpZfXQQrv8yZHQkrsKYPmvIULWz8ZadbMdfN7cE3c5k1fIlTDubJWY=,iv:Z1Ln5JiL+YgOVvlvZHoTQlI32Fy3WLyvTN+0N6zq9G0=,tag:L5iDi2Tj6QSeFzvhi+nM9A==,type:str]
  username: ENC[AES256_GCM,data:BAmQYYExAMF7aV2mBw==,iv:C61ms2H8kRRswCj1Led01wxq22vr3vVF53mS0lnXTik=,tag:amnPvg0yBJYfCdhc2YYTiQ==,type:str]
  password: ENC[AES256_GCM,data:ziulzFW1F6uXpl3orTOi,iv:RlUlP/x4cK+kQe2enV2I4QxAV6DD+M1luWJoYcHJ1ig=,tag:MTecTmnmtWguTE9TBecsAQ==,type:str]
  DB_TYPE: ENC[AES256_GCM,data:QNZPUNJD9I8=,iv:QqRSZpaGWEWf8r4u29i5b9yLyU5aVSFmu/yPs0h5joc=,tag:XO3SN/hmxjuVaNCDbe9lzw==,type:str]
  HOST: ENC[AES256_GCM,data:Lpr22x60fIs=,iv:lEmDl5iJCJPgELM8wv/m+9npnbwr7m5xM1XJFHXEBjo=,tag:eFQ+sbh7/154hgfDqLfiGg==,type:str]
  PASSWD: ENC[AES256_GCM,data:MRdgVhm2aUeVFjiJ1rQTWpTm4ZW/aqE2Dff65MMzRZvmIixM,iv:9uh+j3NuTIPn5YHyYVhgZcxp5C1vQQFUbYUeiqnpqEE=,tag:r0BDch+tw353/YaiNGNjug==,type:str]
  USER: ENC[AES256_GCM,data:wHbTPlFq6Q==,iv:EuJ6SLQpWPtRDZj205LEp7pgXPWz8oAPht6iCw/+IBk=,tag:NkhP4GrE/tSfTN5AvMD3Qw==,type:str]
  NAME: ENC[AES256_GCM,data:EYJV+ZHUUgs=,iv:7fm+e+l9Gpsy+lUsmbJi0MBdpc+69sQWzTHplhX554Y=,tag:xAup8aw65C24HbmkXXiG3g==,type:str]
sops:
  age:
    - recipient: age1fd6r86ze2kzv9fey9y0jx47uekpkjsat76l2t6uesfhjpx7463cqtawww5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejZ0M3I1MHZtR2RtZmg0
        ZE1odlZ1V2kxSTM5VjZmaC85VjV4NmIrQndrCmJYdktYVVNPcitMZS9YSE1BNVN3
        WXpBUndkNUJXWEFVT0twVldqTTBDblUKLS0tIGthNG9GOW5xdWFuanlkT0xZekFa
        NE40enY1a3NZbVljYmpyNDRFSUZ5RTAKZZhEGkeVjJNT+kbv7xyxePum1RfP1OUw
        +RgCoroHJyrxhmPCmoG09BcR4GhWK6pvkXel+qronUrgHNq2BRydag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-13T13:47:47Z"
  mac: ENC[AES256_GCM,data:LIaI86z9nHJCXoeJR65iCp+tTsJ9SA31Yd2aab7Gfcwg/Hrli5e1FiYOijVP1tvUbc8s1lNNSWO96XFqi8IHgMuZk0MUK6h3jLH9L7Gqza5V3rxy47ZFqPGXwdid7LPvk2aErt/mL5X8eLgCUH9Q5U6iWidnq765RARosGYCr/M=,iv:WCH5Zd38I3npzCE7R4o5+42+IdqwWrs7Ziy+pPSO4N4=,tag:qjDCcx0a0ijTSUsZWGjjGg==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.11.0
