initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.13.1@sha256:472d0e486d5d5c23c782b1b123530c7df8645784523ec36ca661a326d47885ff
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
credentials:
  useSecret: true
  existingSecret: cloud-credentials
configuration:
  backupStorageLocation:
    - name: backblaze
      provider: aws
      bucket: myanello-velero
      default: true
      credential:
        name: cloud-credentials
        key: cloud
      config:
        region: us-west-004
        s3Url: https://s3.us-west-004.backblazeb2.com
  volumeSnapshotLocation:
    - name: backblaze
      provider: aws
      bucket: myanello-velero
      default: true
      credential:
        name: cloud-credentials
        key: cloud
      config:
        region: us-west-004
        profile: default
        enableSharedConfig: "true"
deployNodeAgent: true
nodeAgent:
  podVolumePath: /var/lib/kubelet/pods
  privileged: false
  tolerations:
    - effect: NoSchedule
      operator: Exists
    - effect: NoExecute
      operator: Exists
schedules:
  weekly:
    disabled: false
    schedule: "0 4 * * 1" # 4am monday
    paused: false
    skipImmediately: false
    template:
      ttl: "720h" # 1 month 
      storageLocation: backblaze
kubectl:
   image:
      repository: harbor.yanello.net/docker/bitnamilegacy/kubectl
      tag: "1.33.1"