initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.13.2@sha256:25c3a0a043fc396a0593a3da0aa16ed1f39df74883bda42c4588fc8877b72bde
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
credentials:
  useSecret: true
  existingSecret: cloud-credentials
configuration:
  backupStorageLocation:
    - name: backblaze
      provider: aws
      bucket: myanello-velero
      default: true
      credential:
        name: cloud-credentials
        key: cloud
      config:
        region: us-west-004
        s3Url: https://s3.us-west-004.backblazeb2.com
  volumeSnapshotLocation:
    - name: backblaze
      provider: aws
      bucket: myanello-velero
      default: true
      credential:
        name: cloud-credentials
        key: cloud
      config:
        region: us-west-004
        profile: default
        enableSharedConfig: "true"
deployNodeAgent: true
nodeAgent:
  podVolumePath: /var/lib/kubelet/pods
  privileged: false
  tolerations:
    - effect: NoSchedule
      operator: Exists
    - effect: NoExecute
      operator: Exists
schedules:
  weekly:
    disabled: false
    schedule: "0 4 * * 1" # 4am monday
    paused: false
    skipImmediately: false
    template:
      ttl: "720h" # 1 month 
      storageLocation: backblaze
kubectl:
   image:
      repository: harbor.yanello.net/docker/bitnamilegacy/kubectl
      tag: "1.33.4@sha256:ed0b31a0508da84ee655c5c6e01bd3897fc56ad6cf69debb27fa1893a06d2246"