apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tenant-slurm

configMapGenerator:
  - name: bashrc-config
    files:
      - bashrc-config.sh
      - shell-aliases.sh
generatorOptions:
  disableNameSuffixHash: true
