apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: 00-config
    files:
      - ./manifests/config.kdl
  - name: 02-metrics
    files:
      - ./manifests/metrics.kdl  

resources:
  - manifests/sts.yaml
  - manifests/service.yaml
  - manifests/http-route.yaml
  - manifests/scrape.yaml
