apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: config
    files:
      - ./manifests/config.kdl

resources:
  - manifests/sts.yaml
  - manifests/service.yaml
  - manifests/http-route.yaml
  - manifests/scrape.yaml
